name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - id: setupGradle
        name: "🔧 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
      - id: generateVersion
        name: "Generate mod version"
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          search_commit_body: true
          debug: true
          bump_each_commit: true
          version_format: "${major}.${minor}.${patch}"
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        env:
          Version: ${{ steps.generateVersion.outputs.version }}
      - name: Run tests
        run: ./gradlew test --no-daemon
        env:
          Version: ${{ steps.generateVersion.outputs.version }}

