name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - id: setupGradle
        name: "🔧 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
      - id: generateVersion
        name: "Generate mod version"
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          search_commit_body: true
          debug: true
          bump_each_commit: true
          version_format: "${major}.${minor}.${patch}"
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        env:
          Version: ${{ steps.generateVersion.outputs.version }}
      - name: Publish to Maven
        if: success() && steps.generateVersion.outputs.version
        env:
          ForgeMavenUsername: ${{ secrets.MAVEN_USERNAME }}
          ForgeMavenPassword: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew publish --no-daemon

